### ISSUE TITLE
Hamburger(Collapsed) menu doesn't closes on click

### ISSUE THREAD

**Issue by tikhsuP** [joomla/api.joomla.org#16] opened 2020-02-17 15:25 UTC
# Subject of the issue

The Hamburger menu, once opened by a click, can not be closed by another click.
There is no way to close the menu without refreshing the page.

# Steps to reproduce

Click the Hamburger menu to open it.
Now click it again to close it, NOT WORKING.

# Expected behaviour

Clicking the open Hamburger menu should close(collapse) it.

# Actual behaviour
Clicking the open Hamburger menu isn't closing it.

![Screenshot (15)](https://user-images.githubusercontent.com/42881874/74666512-a2ce6b00-51c7-11ea-87cf-48b44f9b6e59.png)

**Comment by mbabker** [comment] 2020-02-17 15:31
Duplicate of https://github.com/joomla/joomla-websites/issues/1211

**Closed by mbabker** 2020-02-17 15:31 UTC

**Comment by tikhsuP** [comment] 2020-02-17 15:39
Thanks.
